# Generated by Django 4.1.2 on 2022-11-20 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={},
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='source',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='description',
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budget_amount',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
    ]
