# Generated by Django 4.1.2 on 2022-11-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budget_amount_budget_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='name',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
    ]
