# Generated by Django 4.1.2 on 2022-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_name_budget_month_remove_budget_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
