# Generated by Django 4.1.2 on 2022-12-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budget_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_amount',
            name='budget_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
    ]
