# Generated by Django 4.1.2 on 2022-12-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budget_amount_budget_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget_amount',
            old_name='budget_id',
            new_name='budget',
        ),
    ]
