# Generated by Django 4.1.2 on 2022-11-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercategory', '0002_remove_usercategory_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
