envVarGroups:
  - name: expense-tracker-shared
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.0"

services:
  - type: web
    name: expense-tracker-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py ensure_superuser && python manage.py seed_demo_data
    startCommand: gunicorn ExpenseTracker.wsgi --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 60
    healthCheckPath: /api/schema/
    envVars:
      - fromGroup: expense-tracker-shared
      - key: DATABASE_URL
        sync: false

  - type: cron
    name: generate-recurring-expenses
    runtime: python
    schedule: "0 0 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py generate_recurring_expenses
    envVars:
      - fromGroup: expense-tracker-shared
      - key: DATABASE_URL
        sync: false

  - type: cron
    name: generate-notifications
    runtime: python
    schedule: "0 1 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py generate_notifications
    envVars:
      - fromGroup: expense-tracker-shared
      - key: DATABASE_URL
        sync: false
