# Generated by Django 4.1.2 on 2022-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersource', '0003_alter_usersource_usersource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersource',
            name='usersource',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
