# Generated by Django 6.0.3 on 2026-05-02 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0007_multi_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["owner", "-date"], name="exp_owner_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["owner", "category", "-date"],
                name="exp_owner_cat_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["owner", "account", "-date"],
                name="exp_owner_acct_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["owner", "is_read", "-created_at"],
                name="notif_owner_read_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["owner", "notification_type", "-created_at"],
                name="notif_owner_type_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringexpense",
            index=models.Index(
                fields=["is_active", "next_run_date"],
                name="recur_active_run_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringexpense",
            index=models.Index(
                fields=["owner", "is_active", "next_run_date"],
                name="recur_owner_active_run_idx",
            ),
        ),
    ]
