# Generated by Django 4.1.2 on 2022-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='usercategory',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
