# Generated by Django 4.1.2 on 2022-11-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_usercategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercategory',
            old_name='category',
            new_name='usercategory',
        ),
    ]
