# Generated by Django 4.1.2 on 2022-11-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_category_usercategory_usercategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
